name: Bug Report
description: Something is broken or behaving unexpectedly
labels: ["bug"]
body:
  - type: dropdown
    id: module
    attributes:
      label: Module
      options:
        - log-analysis
        - ids
        - endpoint-monitor
        - threat-hunting
        - incident-response
        - siem
        - shared
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `python ...`
        2. With input `...`
        3. Error occurs
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        OS: Ubuntu 22.04
        Python: 3.10.12
